ui:
  component:
    applicationName: Swing-Ui
    icon: icon.png
    componentConfigXml: UiComponents.xml
    splashScreen: splashscreen.png
    lookAndFeel: Nimbus
  toolbar:
    toolbarListMap:
      ENVBAR:
        - buttonAction: DEV
          buttonName: Dev
          buttonToolTip: Run Dev Action
        - buttonAction: TEST
          buttonName: Test
          buttonToolTip: Run Test Action
      ACTIONBAR:
        - buttonAction: SAVE
          buttonName: Save
          buttonToolTip: Save Item
        - buttonAction: DELETE
          buttonName: Delete
          buttonToolTip: Delete Item
