//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.23 at 10:11:35 AM IST 
//

package io.smart.swings.x2jparser.builder.components;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TextBox complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TextBox">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="textBoxToolTip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="textBoxName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="textBoxAction" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="textBoxImage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="textBoxXPos" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="textBoxYPos" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="textBoxDisabled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="textBoxListeners" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextBox", propOrder = { "textBoxToolTip" })
public class TextBox {

	protected String textBoxToolTip;
	@XmlAttribute(required = true)
	protected String textBoxName;
	@XmlAttribute(required = true)
	protected String textBoxAction;
	@XmlAttribute
	protected String textBoxImage;
	@XmlAttribute
	protected String textBoxXPos;
	@XmlAttribute
	protected String textBoxYPos;
	@XmlAttribute
	protected String textBoxDisabled;
	@XmlAttribute
	protected String textBoxListeners;

	/**
	 * Gets the value of the textBoxToolTip property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextBoxToolTip() {
		return textBoxToolTip;
	}

	/**
	 * Sets the value of the textBoxToolTip property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextBoxToolTip(String value) {
		this.textBoxToolTip = value;
	}

	/**
	 * Gets the value of the textBoxName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextBoxName() {
		return textBoxName;
	}

	/**
	 * Sets the value of the textBoxName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextBoxName(String value) {
		this.textBoxName = value;
	}

	/**
	 * Gets the value of the textBoxAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextBoxAction() {
		return textBoxAction;
	}

	/**
	 * Sets the value of the textBoxAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextBoxAction(String value) {
		this.textBoxAction = value;
	}

	/**
	 * Gets the value of the textBoxImage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextBoxImage() {
		return textBoxImage;
	}

	/**
	 * Sets the value of the textBoxImage property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextBoxImage(String value) {
		this.textBoxImage = value;
	}

	/**
	 * Gets the value of the textBoxXPos property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextBoxXPos() {
		return textBoxXPos;
	}

	/**
	 * Sets the value of the textBoxXPos property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextBoxXPos(String value) {
		this.textBoxXPos = value;
	}

	/**
	 * Gets the value of the textBoxYPos property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextBoxYPos() {
		return textBoxYPos;
	}

	/**
	 * Sets the value of the textBoxYPos property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextBoxYPos(String value) {
		this.textBoxYPos = value;
	}

	/**
	 * Gets the value of the textBoxDisabled property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextBoxDisabled() {
		return textBoxDisabled;
	}

	/**
	 * Sets the value of the textBoxDisabled property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextBoxDisabled(String value) {
		this.textBoxDisabled = value;
	}

	/**
	 * Gets the value of the textBoxListeners property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTextBoxListeners() {
		return textBoxListeners;
	}

	/**
	 * Sets the value of the textBoxListeners property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTextBoxListeners(String value) {
		this.textBoxListeners = value;
	}

}
